/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>

unsigned char variable1;
uint8_t variable2 = 0xFF;
uint32_t variable3;
uint16_t variable4;

uint8_t x,y,z;
int16_t m=2,n=3,l=-5;

char miPrimerString[5]="Linux"; // para guardar un string se utiliza un char y en los corches se pone el numero de letras que tenga el string

char miPrimerCaracter = 'A'; //para definir un solo caracter

uint8_t variable5; int32_t variable6;


int main(void)
{
	//Esta es una prueba
	char sizeChar = sizeof(char); //nos da el tamaño de la variable en byte
	(void) sizeChar;

	m = m + n;
	m += n;
	m = m + 1;
	m += 1;
	m ++;

	m *= n;
	m /= n;

	m %= n;

	m <<= n;

	m >>= n;


//en operaciones booleanas cualquier numero diferente de cero es true
	char clearVar = 0b11110110;
	char clearMask = 0b01111111;

	clearVar = clearVar & clearMask;
	clearVar = clearVar & ~(1<<7);
	clearVar &= ~(1<<7);

	char setVar = 0b10010111;

	char setMask = 0b01000000;

	setVar = setVar | setMask;

	setVar |= (1<<6);

    /* Loop forever */
	while(1){

	}
}
